### PR TITLE
Add VC++ 2022

### LINKED ISSUE #3: Does not capture latest c++ version
Love the library - exactly what I was looking for, but I think it needs an update for new versions?

https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160

### PR DESCRIPTION
**Pull request by amaitland**
- Adds entries for two new VC++ versions.

Resolves #3

### CODE REVIEW

**Comment by enclave-marc-barry** [comment]
Thanks for the contribution @amaitland

**Comment by amaitland** [comment]
No problem. Just realised I forgot to update https://github.com/enclave-networks/mscversion#detected-versions to add `2022` to the list. Let me know if you would like another `PR`.

**Comment by enclave-marc-barry** [comment]
That's okay, have just updated it

**Comment by HebaruSan** [comment]
Hi @enclave-marc-barry, thanks so much for maintaining this package. The [version on Nuget](https://www.nuget.org/packages/MscVersion/#versions-body-tab) seems to not have this PR's changes (being 2 years older), which has meant that the code I'm writing to use this library only detects up to VS2013 even though I have the latest runtime installed.

I'm sorry if it is presumptuous to ask this, but could you please ship a new release? Being able to detect the latest runtime would be quite useful. Thank you!

**Pull request merged**
